### ISSUE TITLE
Left page header showing previous page

### ISSUE THREAD

**Issue by pongloongyeat** [charlesLucky/Monash-Thesis-Template-Latex#1]
As title implies. Referring to the image below, "Symbols" should not appear on the header as this is Section 1.0 and past the Symbols page.

![image](https://user-images.githubusercontent.com/31680656/116507107-341f8e00-a8f1-11eb-8c1c-02d8be8f204e.png)

**Comment by pongloongyeat** [comment]
Also, is having the first page of the main matter show its page numbering on the bottom intentional? I can't seem to get this to move to the top header

**Comment by xingbod** [comment]
@pongloongyeat Thanks so much for the help.
